### ISSUE TITLE
`AllowableDeviations.NONE` vs setting `SyslogParserBuilder.deviations` to be empty

### ISSUE THREAD

**Issue by aSemy** [palindromicity/simple-syslog#20]
I think `AllowableDeviations.NONE` is redundant - 'no deviations' can already be represented by setting `SyslogParserBuilder.deviations` to be empty.

I propose removing `AllowableDeviations.NONE`

https://github.com/palindromicity/simple-syslog/blob/fd849bdec5dc25716b6e327bfedc07c761aac134/src/main/java/com/github/palindromicity/syslog/AllowableDeviations.java#L24-L27

And updating the documentation, for example this Javadoc:

https://github.com/palindromicity/simple-syslog/blob/fd849bdec5dc25716b6e327bfedc07c761aac134/src/main/java/com/github/palindromicity/syslog/SyslogParserBuilder.java#L26-L29

**Comment by ottobackwards** [comment]
I prefer to have my enumerations to be complete.  The type is different than the use of the type in the api which is circumstantial and external to the type.
