### ISSUE TITLE
Add `@Nullable`/`@NonNull` annotations on parsed values

### ISSUE THREAD

**Issue by aSemy** [palindromicity/simple-syslog#21]
It would be very helpful if there were `@Nullable`/`@NonNull` annotations on the returned parsed Map to denote whether the value is nullable.

This especially useful in Kotlin, as the Kotlin compiler would then be aware that the returned value might be nullable, and so it improves type safety.

Proposed change:

```java
// AbstractSyslogParser.java

  @Override
  public abstract Map<String, @Nullable Object> parseLine(String syslogLine);
```

One problem I foresee is there's no easy way to only use `@Nullable` if NilPolicy.NULL is set - this might be possible by introducing more generics?

If you do consider adding annotations and you're not sure what one to use, I think [JSpecify](https://jspecify.dev/) is becoming the new standard - but I might be out of the loop.

**Comment by ottobackwards** [comment]
@aSemy please have a look.  I *think* this is correct.  
A couple more little things and I'll see if I can remember how to do a release :)

**Comment by aSemy** [comment]
Looks good at first glance! Thanks a lot, it really helps!

**Comment by ottobackwards** [comment]
@aSemy I have just release v. 1.0.0 with this change in
